accounts/urls.py
from django.urls import include, path

from . import views

app_name = "accounts"


password_reset_urlpatterns = [
    path("", views.MemberPasswordResetView.as_view(), name="password_reset"),
    path(
        "done/", views.MemberPasswordResetDoneView.as_view(), name="password_reset_done"
    ),
    path(
        "confirm/<slug:uidb64>/<slug:token>/",
        views.MemberPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "complete/",
        views.MemberPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

password_change_urlpatterns = [
    path("", views.MemberPasswordChangeView.as_view(), name="password_change"),
    path(
        "done/",
        views.MemberPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
]

account_urlpatterns = [
    path("profile/", views.MemberProfileView.as_view(), name="profile"),
    path("edit/", views.MemberEditView.as_view(), name="profile_edit"),
    path(
        "deactivate/", views.MemberDeactivateView.as_view(), name="account_deactivate"
    ),
    path("delete/", views.MemberDeleteView.as_view(), name="account_delete"),
]

urlpatterns = [
    # user signup
    path("signup/", views.MemberSignUpView.as_view(), name="signup"),
    # user login, logout
    path("login/", views.MemberLoginView.as_view(), name="login"),
    path("logout/", views.MemberLogoutView.as_view(), name="logout"),
    # user profile
    path("my_profile/", views.MemberOwnProfileView.as_view(), name="my_profile"),
    # password reset
    path("password_reset/", include(password_reset_urlpatterns)),
    # password change
    path("password_change/", include(password_change_urlpatterns)),
    # account patterns
    path("<slug:user_name>/", include(account_urlpatterns)),
]

api/urls.py
from django.urls import include, path

app_name = "api"


urlpatterns = [
    path("v1/", include(("api.v1.urls", "api"), namespace="v1")),
    # path("v3/", include(("api.v2.urls", "api"), namespace="v2")),
    # path("v2/", include(("api.v3.urls", "api"), namespace="v3")),
]

dashboard/urls.py
from django.urls import path


from . import views


app_name = "dashboard"

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
]

devices/urls.py
from django.urls import include, path

from . import views

app_name = "devices"

# -----------------------------------------------------------------------------
# Device URLs
# -----------------------------------------------------------------------------
device_edit_urls = [
    # details view
    path("details/", views.DeviceDetailView.as_view(), name="device_details"),
    # edit view
    path("edit/", views.DeviceEditView.as_view(), name="device_edit"),
    # delete view
    path("delete/", views.DeviceDeleteView.as_view(), name="device_delete"),
    # device data list
    path("data/", views.DeviceDataHistoryView.as_view(), name="device_data_list"),
]

device_urls = [
    # create view
    path("create/", views.DeviceCreateView.as_view(), name="device_create"),
    # list view
    path("list/", views.DeviceListView.as_view(), name="device_list"),
    # details, edit, remove and deactivate views
    path("<slug:device_uid>/", include(device_edit_urls)),
]

# -----------------------------------------------------------------------------
# Device Group URLs
# -----------------------------------------------------------------------------
group_edit_urlpatterns = [
    # details view
    path("details/", views.DeviceGroupDetailView.as_view(), name="group_details"),
    # edit view
    path("edit/", views.DeviceGroupEditView.as_view(), name="group_edit"),
    # delete view
    path("delete/", views.DeviceGroupDeleteView.as_view(), name="group_delete"),
]

group_urls = [
    # create view
    path("create/", views.DeviceGroupCreateView.as_view(), name="group_create"),
    # list view
    path("list/", views.DeviceGroupListView.as_view(), name="group_list"),
    # details, edit and remove views
    path("<slug:group_name>/", include(group_edit_urlpatterns)),
]

# -----------------------------------------------------------------------------
# Device Data URLs
# -----------------------------------------------------------------------------
device_data = [
    path("<int:pk>/", views.DeviceDataDetailsView.as_view(), name="data_details"),
    path("list/", views.DeviceDataListView.as_view(), name="data_list"),
]

# -----------------------------------------------------------------------------
# Device Application URLs
# -----------------------------------------------------------------------------
urlpatterns = [
    path("", include(device_urls)),
    path("group/", include(group_urls)),
    path("data/", include(device_data)),
    path("search/", views.DeviceSearchResultsView.as_view(), name="search"),
]

sia/urls.py
from django.contrib import admin
from django.urls import include, path

from dashboard import views as dashboard_views


api_urlpatterns = [
    # api
    path("", include("api.urls")),
    
    # api authentication
    path("auth/", include("rest_framework.urls", namespace="rest_framework")),
]


urlpatterns = [
    # admin
    path("admin/", admin.site.urls),
    
    # accounts
    path("accounts/", include("accounts.urls")),

    # devices
    path("device/", include("devices.urls")),
    
    # dashboard
    path("dashboard", include("dashboard.urls")),

    path("api/", include(api_urlpatterns)),
    
    # homepage
    path("", dashboard_views.DashboardView.as_view(), name="homepage"),
    
    # debug toolbar 
    path('__debug__/', include('debug_toolbar.urls')),
]

common/forms/mixins.py
from typing import *

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class NoSaveMixin:
    def save(self, commit: bool = True) -> Any:
        commit = False
        return super().save(commit)


class UniquePasswordMixin:
    unique_password_error_messages = {
        "unique_password": _("New password must be different from old password")
    }
    
    def clean_new_password2(self) -> str:
        new_password2 = self.cleaned_data.get("new_password2")
        if self.user.check_password(new_password2):
            raise ValidationError(
                self.unique_password_error_messages["unique_password"],
                code="unique_password",
            )
        return super().clean_new_password2()


class UniqueUsernameMixin:
    unique_username_error_messages = {
        "unique_username": _("A user with that username already exists."),
    }
    
    def clean_username(self):
        """Make sure the username is unique (case insensitive), only if the username field was changed"""
        username = self.cleaned_data.get("username")
        if self.changed_data and "username" in self.changed_data and self._meta.model.objects.filter(username__iexact=username).exists():
            raise ValidationError(self.unique_username_error_messages["unique_username"], code="unique_username")
        return username


class UniqueDeviceGroupPerMemberMixin:
    """Check if device group's name is unique for the current owner, requires self.owner attribute"""
    
    error_messages = {
        "unique_name": "A device group with this name already exists.",
    }
    
    def clean_name(self) -> str:
        group_name = self.cleaned_data["name"].lower()
        if "name" in self.changed_data and self._meta.model.objects.filter(name=group_name, owner=self.owner).exists():
            raise ValidationError(
                self.error_messages["unique_name"],
                code="unique_name",
            )
        
        return group_name


class UniqueDevicePerMemberMixin:
    """Check if device's name is unique for the current owner, requires self.owner attribute"""
    
    error_messages = {
        "unique_name": "A device with this name already exists.",
    }
    
    def clean_name(self) -> str:
        device_name = self.cleaned_data["name"].lower()
        if "name" in self.changed_data and self.owner.devicegroup_set.filter(device__name__iexact=device_name).exists():
            raise ValidationError(
                self.error_messages["unique_name"],
                code="unique_name",
            )
    
        return device_name

common/views/mixins.py
from typing import *

from django.contrib.auth.mixins import AccessMixin, LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy


class MemberLoginRequiredMixin(LoginRequiredMixin):
    """Custom login required mixin, redirects to 'accounts:login' page if not logged in"""
    login_url = reverse_lazy("accounts:login")


class AnonymousUserRequiredMixin(AccessMixin):
    """Verify that the current user is an anonymous user (not logged in)"""
    
    redirect_url: str|None = None

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            return HttpResponseRedirect(self.redirect_url)
        return super().dispatch(request, *args, **kwargs)


class OwnerMemberRequiredMixin(AccessMixin):
    """Verify that the current user is the owner of the object"""
    
    def dispatch(self, request, *args, **kwargs):
        user_name = kwargs.get("user_name")
        user = request.user
        if user.username != user_name:
            self.permission_denied_message = "You do not have permission to access this page."
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

common/templates/base/base_navbar.html
{% comment %} basse/base_navbar.html {% endcomment %}

{% block navbar %}

<div class="nav-site-links">

  {% block homepage %} 
  <div class="navbar_link">
    <a href="{% url 'homepage' %}">Home</a> 
  </div>
  {% endblock homepage %}

  {% block dashboard %}
  <div class="navbar_link">
    <a href="{% url 'dashboard:dashboard' %}">Dashboard</a>
  </div>
  {% endblock %}

  {% block group_list %}
  <div class="navbar_link">
    <a href="{% url 'devices:group_list' %}">My Groups</a>
  </div>
  {% endblock %}

  {% block device_list %}
  <div class="navbar_link">
    <a href="{% url 'devices:device_list' %}">My Devices</a>
  </div>
  {% endblock %}

</div>

<div class="nav-member-links">
  {% if user.is_authenticated %}

  {% block profile %}
  <div class="navbar_link">
    <a href="{% url 'accounts:my_profile' %}">{{ user.username }}</a>
  </div>
  {% endblock profile %}

  {% block logout %}
  <div class="navbar_link">
    <a href="{% url 'accounts:logout' %}">Log Out</a>
  </div>
  {% endblock logout %}

  {% else %}

  {% block login %}  
  <div class="navbar_link">
    <a href="{% url 'accounts:login' %}">Log In</a>
  </div>
  {% endblock login %}

  {% block signup %}
  <div class="navbar_link">
    <a href="{% url 'accounts:signup' %}">Sign Up</a>
  </div>
  {% endblock signup %}

  {% endif %}
  
</div>

<div class="nav-settings">
  {% block settings %} 
  <div class="navbar_link">
    {{ settings }} 
  </div>
  {% endblock settings %}
</div>

{% endblock navbar %}

common/templates/base/base_page.html
{% comment %} base/base_page.html {% endcomment %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {{ title }} {% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'base/css/style.css' %}">
    {% block extra_css %}{% endblock extra_css %}
    {% block extra_js %}{% endblock extra_js %}
  </head>

  <body>
    <nav>
        {% include 'base/base_navbar.html' %}
    </nav>

    <div>
      {% include 'base/base_search_bar.html' %}
    </div>

    <main>
        {% block body %} {{ body }} {% endblock body %}
    </main>

    <footer>
        {% block footer %} {{ footer }} {% endblock footer %}
    </footer>
  </body>

</html>

common/templates/base/base_pagination.html
<script>
  function addPagination(page) {
    var url_query = window.location.search;
    // remove trailing "/"
    if(url_query.endsWith("/")){
      url_query = url_query.slice(0, -1);
    }

    if (url_query == ""){
      // url has no query string --> add "?page="
      return "?page=" + page;
    } else if(url_query.includes("page=")) {
      // url has a "page" key in query string --> replace "page=" value
      return url_query.replace(/page=\d+/, "page=" + page);
    } else {
      // url has a query string but no "page" key --> add "&page="
      return url_query + "&page=" + page;
    }
  }
</script>

{% if page_obj.has_previous %}
<button onclick="window.location.href = addPagination(1)">First</button>
<button onclick="window.location.href = addPagination({{ page_obj.previous_page_number }})">Back</button>
{% else %}
<button onclick="window.location.href = addPagination(1)" disabled>First</button>
<button onclick="#" disabled>Back</button>
{% endif %}

<span class="current">
  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
</span>

{% if page_obj.has_next %}
<button onclick="window.location.href = addPagination({{ page_obj.next_page_number }})">Next</button>
<button onclick="window.location.href = addPagination({{ page_obj.paginator.num_pages }})">Last</button>
{% else %}
<button onclick="#" disabled>Next</button>
<button onclick="window.location.href = addPagination({{ page_obj.paginator.num_pages }})" disabled>Last</button>
{% endif %}

common/templates/base/base_search_bar.html
{% if search_form is not None %}
<hr>
<div>
  <h2>Search</h2>
</div>
<div class="form-container">
  <form action="{% url 'devices:search' %}" method="GET">
    {{ search_form.as_div }}
    
    <div>
      <button type="submit">Search</button>
    </div>
    
  </form>
</div>
<hr>
{% endif %}